development:
  bucket_name: htllc-mec-vivek
  access_key_id: secretkeyid
  secret_access_key: secretaccesskey
production:
  bucket_name: <%= ENV["MEC_AWS_BUCKET"] %>
  access_key_id: <%= ENV["MEC_AWS_ACCESS_ID"] %>
  secret_access_key: <%= ENV["MEC_AWS_ACCESS_SECRET"] %>
test:
  bucket_name: htllc-mec-vivek
  access_key_id: secretkeyid
  secret_access_key: secretaccesskey