# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8dc889326bdb427ec9f013985604328ca558753ceee6ebfa2abc74fd92a4b4713b21eef285a1f5eb78126c178205198e2d95539b8d41bd770c82f01c150baf3

test:
  secret_key_base: 38ed1defa3ad49519579515530e1474d37bef89f43da107d6582ba93784202e2da0211b109856079b6094e9c0e711245c051fc4eed9089f152802c2e877d7bf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
